version: '1'

services:
  airflow:
    image: airflow_image
    environment:
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://root:root@postgres:5432/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://root:root@postgres:5432/airflow
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
    ports:
      - 8080:8080
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/opt/data
      - ./scripts:/opt/scripts
    links:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER:root
      - POSTGRES_PASSWORD:root
      - POSTGRES_DB=airflow
    volumes:
      - /home/angelo/Documentos/Cursos/projeto_agro/airflow/metadata_airflow:/var/lib/postgresql/data
    ports:
      - 5430:5432

  scheduler:
      image: airflow_image
      command: [ "airflow", "scheduler" ]
      environment:
        - AIRFLOW_HOME=/opt/airflow
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://root:root@postgres:5432/airflow
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://root:root@postgres:5432/airflow
        - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/logs:/opt/airflow/logs
        - ./data:/opt/data
        - ./scripts:/opt/scripts
      links:
        - postgres
